Feature/clerax backend
franciscojho/clerax-app-backend pull request #1
Opened 2022-03-09 21:33 UTC by franciscojho

Clerax backend using express, express-validator and moongose. It is connected to MongoDB Atlas.

2022-03-10 14:06 UTC, Drleugim requested changes

2022-03-10 14:06 UTC, Drleugim commented on src/middlewares/validateUid.js
> +        // let user
Remove commented code pls

2022-03-10 20:34 UTC, franciscojho commented on src/middlewares/validateUid.js
> +        // let user
Updated, please review it again.

2022-03-11 00:57 UTC, Drleugim approved these changes
LGTM

2022-03-16 18:00 UTC, merged